In [1]:
import glob
import pandas as pd

In [2]:
clean_data_ridership = pd.concat([pd.read_csv(f) for f in glob.glob('*.csv')], ignore_index = True)

In [3]:
clean_data_ridership.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,...,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,266.0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273.0,Manila & 1st,40.721651,-74.042884,3209.0,Brunswick St,40.724176,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1543.0,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681.0,Grand St,40.715178,-74.037683,3213.0,Van Vorst Park,40.718489,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1461.0,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681.0,Grand St,40.715178,-74.037683,3213.0,Van Vorst Park,40.718489,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,793.0,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185.0,City Hall,40.717732,-74.043845,3199.0,Newport Pkwy,40.728745,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,596.0,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639.0,Harborside,40.719252,-74.034234,3209.0,Brunswick St,40.724176,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
clean_data_ridership.count()

tripduration               348426
starttime                  348426
stoptime                   348426
start station id           348426
start station name         348426
start station latitude     348426
start station longitude    348426
end station id             348426
end station name           348426
end station latitude       348426
end station longitude      348426
bikeid                     348426
usertype                   348426
birth year                 348426
gender                     348426
ride_id                     90821
rideable_type               90821
started_at                  90821
ended_at                    90821
start_station_name          90821
start_station_id            90821
end_station_name            90495
end_station_id              90495
start_lat                   90821
start_lng                   90821
end_lat                     90495
end_lng                     90495
member_casual               90821
dtype: int64

In [5]:
clean_data_ridership.to_csv("clean_data.csv")